# Generated by Django 4.0.4 on 2022-05-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('1', 'Male'), ('0', 'Female')], default='1', max_length=1)),
                ('cp', models.PositiveSmallIntegerField()),
                ('trestbps', models.PositiveIntegerField()),
                ('chol', models.PositiveIntegerField()),
                ('fbs', models.CharField(choices=[('1', '>120'), ('0', 'Female')], default='1', max_length=1)),
                ('restecg', models.SmallIntegerField()),
                ('thalach', models.SmallIntegerField()),
                ('exang', models.SmallIntegerField()),
                ('oldpeak', models.SmallIntegerField()),
                ('slope', models.SmallIntegerField()),
                ('ca', models.SmallIntegerField()),
                ('thal', models.SmallIntegerField()),
                ('target', models.SmallIntegerField()),
            ],
        ),
    ]
