# Generated by Django 4.0.4 on 2022-05-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='fbs',
            field=models.CharField(choices=[('1', '>120'), ('0', '<120')], default='1', max_length=1),
        ),
    ]
