# Generated by Django 4.0.4 on 2022-05-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_alter_heart_fbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kidney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.SmallIntegerField()),
                ('bp', models.SmallIntegerField()),
                ('sg', models.FloatField()),
                ('al', models.SmallIntegerField()),
                ('su', models.SmallIntegerField()),
                ('rbc', models.BooleanField()),
                ('pc', models.BooleanField()),
                ('pcc', models.BooleanField()),
                ('ba', models.BooleanField()),
                ('bgr', models.BooleanField()),
                ('bu', models.SmallIntegerField()),
                ('sc', models.FloatField()),
                ('sod', models.SmallIntegerField()),
                ('hemo', models.FloatField()),
                ('pcv', models.SmallIntegerField()),
            ],
        ),
    ]
