# Generated by Django 4.0.4 on 2022-05-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_kidney'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.SmallIntegerField()),
                ('gender', models.BooleanField()),
                ('total_bilirubin', models.FloatField()),
                ('direct_bilirubin', models.FloatField()),
                ('alkaline_phosphotase', models.SmallIntegerField()),
                ('alamine_amino', models.SmallIntegerField()),
                ('total_proteins', models.SmallIntegerField()),
                ('albumin', models.FloatField()),
                ('albuumin_and_glubin_ratio', models.FloatField()),
            ],
        ),
    ]
